// Estonian slang terms and phrases from KEELETEADLANE JA SLÄNGIDOKUMENTALIST
const slangTerms = [
    "Uputab... (korvpallis skoorimise kohta)",
    "Lilliputin - teadagi kes",
    "Vanamees alias Vana mees",
    "vaimne prostitutsioon - see mida mina teen",
    "Spordikommide ärakasutamine vestluses",
    "neelata lõtva",
    "esteedid",
    "pritisin mikriisse sülge",
    "kantri-shit",
    "võtame kalja - teeme nalja",
    "roppu rööki",
    "Aastal 82 loom puurist välja last",
    "ülemise riiuli bling bling keti koera",
    "status quo",
    "kulgen kuukaardiaga",
    "Ma pole elupõletaja vaid vahetu realist",
    "kui näen, võtan aktiivset lindu, ei meeldi passiivsed",
    "Ma pole playboy, kuid nussin kuis jaksan",
    "Väikse joogi peale naksan",
    "ringi tsillin, naisi nillin",
    "hundijala sõiduvees",
    "fakti ette seadma - face the facts",
    "mus tärkab aednik susse istutan sette",
    "Kõige nooremale anname sõitu",
    "Hozjain",
    "Mul on täitsa paekas",
    "Oksad on laiali ja Grappat joon",
    "See tuust on libu",
    "igast pasast jututeemat leidsime",
    "Kas see puudel su jalgevahel elab ka",
    "reguleerin asju nagu Haljala valgusfoor",
    "Hetkel möllab likviidne vorm",
    "esoteeriline",
    "Labiilne",
    "Ei tekita, ainult viin",
    "infokäive, süntees, antitees",
    "Milline on sinu tees. 10 teesi",
    "igasugu macho asju teen",
    "nightman",
    "tantsusaalide ülemus",
    "See on elusstiil, see on fun",
    "balance",
    "Aga pliis, natuke enesekriitikat",
    "Sina rähn ei mölise",
    "Saata vittu, kuradi kinnas",
    "Rakvere pätiräpp",
    "Profülaktika",
    "Komprommisitu võitleja",
    "Ennastsalgav",
    "Tänane kreedo",
    "Polemiseerin",
    "Sinu positsioon mängulaual",
    "Parem on saada tervitatud kui kuritarvitatud",
    "Tee emotsioonianalüüs",
    "FEIL",
    "Feel the difference",
    "Samal ajal klubiis, rodeo kuubiis",
    "Poisid ja tüdrukud",
    "Kepitamas",
    "kosmopoliit",
    "Emo - emolaks",
    "Himbo-Jimbo",
    "Slip n Slide, lock and load, in it to win it",
    "Kolõvani naised",
    "naiivne nagu muster köögikitlil",
    "tuju on ultra",
    "Nüüd väike bluus",
    "Or do you wanna be a reindeer",
    "Toastin, toastin 1,2,3",
    "Romantiline võrgutusstiil",
    "Tüüned kärsad",
    "Reo, Reolast vist",
    "Kõigil klik on sees",
    "Otse haljas alla",
    "Tsentrumisse",
    "Päkapikk suus",
    "Diskokuul",
    "110 % vastupandamatut sarmi",
    "Üksi vastus ei lukustu",
    "Lukustame ära",
    "Ilmselgelt, ilmtingimata",
    "Kahehtusväärne juhtum, lugu",
    "Pensik värk",
    "rudistamine ja mudistamine",
    "vuugivahe, puhas vuuk",
    "Võrrisadul",
    "Etanool, metanool",
    "Elokuvat...kubiseb ideedest, samadest klišeedest",
    "Subjekt",
    "Ma külmutan selle miljoni juures",
    "Kaanepoiss",
    "Või diktoriks ETVs",
    "Wrappime sisse, pakime kokku",
    "Kiired sääred",
    "Roadie, taustakeppija, ristsoo Peeter",
    "SeaTiit",
    "Up N Down, 6-Pack, säravad tähed",
    "I was born ready, ma olin sündides valmis",
    "Parastav naer",
    "Pornokuninga piinad",
    "sitt on vedel, heavy shit, shit happens",
    "Ja nüüd breik",
    "mängivad rolle, teevad avaldusi lolle",
    "Steitment pliis",
    "Kaltsupea, El Jeffe",
    "Spetsiaal, special, eripruul",
    "Pärnu meeõlu, kesv, piss, märjuke",
    "Dipp, deep, sombuurne",
    "Dementsus",
    "Embrüo ja Tentro",
    "Pontsik, Fatboy, Ronnie Wood",
    "Keith Richards",
    "Village people, NMKÜ, ETA, FSB",
    "All The Way, lõpuni",
    "Kuuldel, over, Pealuu kutsub Punast Kütti",
    "Verine sea pea",
    "In it to win it",
    "Punchline",
    "7 vaprat, tsirkusetuur",
    "Laadima",
    "get reaal",
    "Peksupealinn",
    "reaalsustaju kaotama",
    "Leo täht",
    "staarikvaliteet, staarigeen",
    "edumeelne, eesrindlik",
    "Hoidised, hoidiseid tegema",
    "Jimmy unistaja",
    "About Schmidt",
    "Thats the one",
    "Ülemus. võll",
    "Big Ding a Ling",
    "Down Low",
    "King Salaami",
    "Drum n Space - Ryan",
    "Väike naps, väike õlu, tuju hea",
    "Ruulige kaasa PimpTVga",
    "Tantsumuusika karmimate teemadega",
    "Kruntima, väikse krundi võiks alla teha",
    "Kolhoosi parim",
    "Sohvoosi edumeelseim",
    "Traktorist, lüpsimasina operaator",
    "Juuksemetall, hairmetal",
    "Immanentne - esemele loomupäraselt omane",
    "Sada ja seened, hevi peale ja vorstikastet",
    "Nõulaifer",
    "Klubipiff, piff",
    "stonerrokk",
    "Peoleo, peoleo skeem",
    "Skeemitama",
    "JOKK - juriidiliselt on kõik korrektne",
    "mul on rakused lünkade täitmisel",
    "Androgüün, MILF, nümf, nümfomaan",
    "Kuule, mine lõigu ennast kuskil",
    "Weird shit",
    "nokuga tibid - emo",
    "hõbekõri",
    "Käed on kuldsed - kõri ka",
    "kobedus kuubis, jubedus ruudus",
    "Graffity, break-dance, dj, elustiil",
    "Haara elul munadest",
    "in oder auss",
    "wassever",
    "no big deal",
    "rüübe",
    "defitsiitne kaubariiul",
    "autopede, spordipede, musapede",
    "Downlow - Johnny B",
    "Püksid pehmet täis",
    "Jubdus kuubis",
    "Indigolapsed - Indigomees",
    "Ylos ja Alas",
    "Sünergia",
    "Pealegi rüüpamata",
    "Masendusvabrik",
    "Avantüristlik, läks avantüürile",
    "Kiibitseja",
    "Odratolgus, Nisu Ants",
    "EPedeeepos",
    "Sõnnikuleht",
    "Vändagänster ja sugumürsk",
    "Kremli ööbik",
    "Kimuma, konelema, näsama, tahmama",
    "ülesannete kõrgusel",
    "Ei saanud linti lahti",
    "Pille R. Kaar",
    "Kõike kaunist",
    "Tervist tütreke",
    "Massive, massiivne",
    "Massiga ikka massiga",
    "Praegu teen massi, varsti hakkan mahtu tegema",
    "Põhikärbes",
    "Elegantne sisenemine",
    "Hiiu Kalur, Mõigu KEK",
    "Strateegiakoosolek - Ema anna padruneid",
    "Sarjast Suuri mõtlejaid",
    "Palju õnne argipäevaks",
    "Ruiin -rutiin tapab, rudiment",
    "B-poiss",
    "Kaader koos, kateeder",
    "Telekokk, florist ja",
    "Element",
    "Pedant, pedantne",
    "Baaris elu käib",
    "Nii see baari elu käib",
    "marlboro mees ja harley davidson",
    "Tango & Cash",
    "Kohaliku tähtsusega",
    "Kotid paneme taha!",
    "Töödejuhataja on objektile saabunud",
    "Tark ei torma",
    "Tunne oma vaenlast",
    "Lihtsalt ei tereta",
    "Tõsielusari",
    "Kimon",
    "Elu pärast baari",
    "Jumal tänatud, et sa siin oled",
    "Mainige",
    "Ma olen shiuke metro",
    "Ma olen shiuke kosmo",
    "Goiko Mijic",
    "Anti, Anti",
    "Sensatsiooniline, fantastiline",
    "See ei ole uni",
    "Elu mis möödub on ilus",
    "Ma kordan uuesti - see ei ole molekul",
    "viimase vindi",
    "Viimase sõna",
    "Weekend warriors",
    "eat the worm motherfoker",
    "MO",
    "Moes",
    "Päris nutine värk siis",
    "Dude, yeahh duud, fuck yeah",
    "Fuck jaaa",
    "Kärss, tüüne kärss",
    "Nokkloom",
    "Turo Turp",
    "Jaak",
    "It rains, it pours",
    "klaaspärlimäng",
    "Zeitgeist - ajastu vaim",
    "OOo tere",
    "No mis minagi",
    "Tere kõik gängsterid ja gängsterinnad",
    "Oleme kogunenud siia looduskaunisse kohta",
    "Plaadispinnija",
    "Lukku lüüa",
    "Vana nälg ise",
    "Asfaldilapsed, idiootide kateeder",
    "Isa soovitusel ja ma tegin seda",
    "Kuid mul ei õnnestund see",
    "Võin kindel olla,.t see mul õnne ei too",
    "Ahh mina või",
    "Perse suunab",
    "Mine munni Mardo",
    "Vilista sussi",
    "Härra treener",
    "Uneleja",
    "Emolaks, emolitter, emotsoon",
    "Emake loodus",
    "No shit sherlock",
    "Noore folkloristina",
    "ma mõtlen",
    "Adreka laks",
    "Hele Laks, Tume laks",
    "Heledad laksud käivad",
    "Miks ma küsin",
    "Juba niiöelda aegunud",
    "Villu, Villu",
    "Sellega ei saa ainult peale minna",
    "Valimatult",
    "Et tekiks dissonants",
    "Kui te mu mõttekäigust aru saate",
    "Loomulikult pedaleerin labasusel",
    "Mis on minu roll",
    "Tere päevast ...doktor",
    "Üksik hunt leiab alati tee",
    "Selleks, et neid võita",
    "Tere Tallinn",
    "See on mingi törts, selline relv",
    "Väga õrn, põhiline värk",
    "täielik diil",
    "rahvakunstnik, loomeinimesed",
    "Jõhker püss",
    "Kaks on lasteaed",
    "See on lõbus, see on fun",
    "Fantoom möllab",
    "Tule taevas appi",
    "Wattzup biitches",
    "Printsipiaalne vastaseis",
    "Me lähme tuuste sahmima",
    "Tuust",
    "Muidu, muide",
    "Oma tuust ei eruta",
    "See on raskekujuline nikunälg",
    "Püha playboy",
    "nagu bändid kes on nunnud",
    "türa teed on ettearvamatud",
    "Mees on rääkinud",
    "Paranoikud",
    "virelevate silmadega ametnikke",
    "südame rütmid murtud",
    "murtud rütmid",
    "teater, kino, muusika",
    "defineerimatus",
    "ajab uimast",
    "Paksu pahandust",
    "Fuckin in the bushes",
    "Referents grupp",
    "Nopime vilju paranoiapuult",
    "Muidugi pedaleerin labasusel",
    "Septembrikuus kõik on uus",
    "Karukägistaja",
    "Kepp ja küla ehk Seks ja Linn",
    "Ajab sellist kägu",
    "Müügiprimaat",
    "Tõlkes kaduma läinud",
    "Tõehetk",
    "Et suvi ei läheks luhta",
    "Vana külalislahkus",
    "Mustika keskuse lihalett",
    "Lihalett, lihaturg",
    "Allrighty",
    "Hurmur, hurmuri, latiinohurmur",
    "Chiba Chiba",
    "Sir Smoke A Lot",
    "Copkilla",
    "Võibolla kuskil ringi kõnnib maffia",
    "O culo",
    "Meditsiiniajakiri",
    "Staarfotograaf, staarjuuksur",
    "Millised formaliteedid",
    "Ja kotid paneme taha",
    "Elamused, ma ütleksin",
    "Hoia oma koeri lühema keti otsas",
    "Eesrindlik mõte",
    "Kui kristalselt aus olla",
    "Mine siku vittu",
    "Bender, Bentoni piparkook",
    "B.S.",
    "Flick",
    "Kick back and enjoy",
    "Sangad Sangastest",
    "Sai ja Piff",
    "Street Smart",
    "Street Cred",
    "Kredibiilne, credibility",
    "juuksenõelakurv",
    "Fööni all olema, auru all olema",
    "keebekas",
    "Party-bong",
    "Loob/hakkas looma",
    "Tutsama, tuts, tutsud sisse",
    "tutsab hästi",
    "Käib hästi",
    "lööke absorbeerima",
    "Võta sisse",
    "Oda panema",
    "Staarinimene",
    "Monokulm, Ükskulm, Unibrow",
    "Constantly fishing for compliments",
    "Mida sa kalastad",
    "Liquid",
    "Pealiskaudsus väänab kõveraks",
    "Counterbluff",
    "Kure motiiv",
    "Motiiv-seniil, debiil",
    "Gaylord",
    "elutreener",
    "tulitav teema, põletav issue",
    "õnnepank, õnnebalee",
    "big no no to the",
    "See on koolitaja jutt",
    "Protect yourself before you wreck yourself",
    "Early bird - varajane lind",
    "Dada - mis see on",
    "Skeene",
    "Klubiahv, glämmiseltskond",
    "Väike intrigeerimismoment",
    "Lajatab rajusid loosungeid",
    "Sellin dzhäss hakkabki toimuma",
    "Midagi tahedamat, vahest meeldib ka pasta",
    "Pärl, pärlid - pearls girl",
    "Jaak väljub liftist",
    "Jaak tahab väljuda",
    "Su kehal on sulle sõnum",
    "Mõni hele laks",
    "Vabandge mu prantuse keelt",
    "Loetud sõna",
    "Keigar",
    "Cool Customer",
    "The house always wins",
    "Joe Schmoe",
    "Gambler",
    "Sarkasm kasutusel",
    "Jäägem moodsaks",
    "Su peale metafooriga lajatan",
    "Meta",
    "Metro",
    "Selliseid silmuseid juba iga tüüp",
    "Arvamusliider",
    "Tootev töö",
    "Töötlema",
    "Sa oled aus inimene",
    "Kogu lugupidamise juures",
    "Luigelaul",
    "Ood",
    "Rahasüst",
    "Adrekalaks",
    "Notoorne",
    "Butafooria - mis see on",
    "HirmuFaktor",
    "Faktor",
    "Ettepanek tahapaneku suhtes",
    "Wear n Tear",
    "Jõuline elumees",
    "Sisekaemus",
    "Tarnima",
    "Trendsetter",
    "Probleeme ei ole, on ainult infomüra",
    "High 5 Planet",
    "Mannekeen",
    "Rünno",
    "Rally Kalle",
    "Räbal lugu",
    "Oma tuust ei rahulda",
    "Väike Juhanson käib sirge seljaga",
    "Kiizu, kiizud",
    "Kepi MVP",
    "Noakangelane",
    "Desperado",
    "Sulliwan",
    "Bouncie-Bounnce",
    "With a twist",
    "On weeed",
    "Wasssuuuup",
    "Seemendama",
    "Väetama, Virtsa-Pille",
    "Tipsutama",
    "Dance like Bez",
    "High like a faaking Kite",
    "Seksrevolutsioon toimus juba ammu",
    "Ja näkineidu hoian kirbul",
    "Sa ka kargu alla ajanud",
    "Loterii allegrii",
    "Bemerast",
    "Huvid - naine ja suur raha",
    "Haara mikker",
    "Võta või jäta",
    "see vastus on tõde",
    "Eestikas",
    "Helsingi on täna haige",
    "elukohajärgses",
    "Kardolas",
    "Postmodern",
    "Post",
    "JJ, KK, Kaarel Kose",
    "provokaator",
    "Ärgem allugem provokatsioonidele",
    "Segregatsioon",
    "Viinahiir, Eurohirv",
    "Müstika, mütoloogiline kuju",
    "Kaljukindel",
    "Asendusmaksumus",
    "Back in bussiness",
    "Cuttima",
    "Suur mäng, suures mängus",
    "Suures mängus kaasa rääkima",
    "Mihkel Roosme",
    "Rariteet",
    "Rudiment",
    "Spordiheeros",
    "Zip-Zip",
    "Diskrediteerida",
    "puistamine, puistama",
    "Esitama kahtlustus",
    "Operatiiv, operaator",
    "Defence Union",
    "JoppAntoonio",
    "Pronksine lugu",
    "Magushapu",
    "Carte Blance - avatud kaartitega",
    "Mängime elu",
    "Ühte väravasse",
    "Tunnetega manipuleerija",
    "Nähtamatu käsi",
    "Taustakeppija",
    "Moekeiser Elmar Seljanka",
    "Parakoksaalne",
    "Huuugo Boss",
    "Tuleb möönda",
    "Slaher, Slashdot",
    "merkantiil, merkantiilne",
    "Metsik Mesi",
    "Titaan",
    "Pseudo",
    "Pseudokuulsus, Fake-celebrity",
    "Ameerika Unelm",
    "Markantne",
    "Legend",
    "kõik on makstud",
    "Bce naazeee",
    "VS kokk Zenja",
    "Aus ja hea",
    "Mujers, neidised",
    "FC Hollywood",
    "Nivooo",
    "Kompromisside kunst",
    "Knife-Knife",
    "Lazyyy",
    "Maaletooja",
    "Paradice",
    "Eesti Naine, Burda, Pere&Kodu",
    "Läheb Kaubaks",
    "Äärmuslik",
    "Lahtiste kätega",
    "Klassikaline ilu",
    "Reaalselt",
    "Kelle jalas on püksid",
    "Kolumn, ei nupp",
    "Sularahakeeris",
    "See kasum",
    "Haare, tegelik haare",
    "Üle rajooni",
    "hitid ainult hitid",
    "Slava käsi",
    "Absoljuuutne see sama",
    "Roteeruma",
    "Asjaga tegelatakse",
    "Kallis ma kahandasin lapsed",
    "Rate on elu",
    "sa oled kaunilt kortsus",
    "Võta oma jope",
    "Kõike kaunist",
    "Mittevähe",
    "Täiskasvanud inimene",
    "Raevukalt",
    "next door, backdoor",
    "Tõmbaks aperatiiviks väikse passoodoobli",
    "Kas teie tantsukaardil on veel ruumi",
    "Niiske kamm ja viimistletud randmetõmme",
    "Seitel korras",
    "Oled saabunud jahile",
    "Tantsupärastlõuna",
    "Elvis has left the building",
    "Kaks jeesust on peal - 66",
    "Spartaki poksitšempion",
    "Võimutseb tango",
    "Sakša šlaager",
    "Kiibitsema",
    "Kannapöörded j puusanõksud",
    "Valivad daamid",
    "Kiievi Dünamo ründaja",
    "Kenad prouad...ka neid on",
    "Kurameerima",
    "See pole nurjatu kuramaaz",
    "Tüpaaaz, tüübikinnitus",
    "Miks tassida puid metsa",
    "Kohali Cassanoova"
];

// Generate additional rhyme pairs and word associations
const wordAssociations = {
    "elu": ["elustiil", "fun", "balance", "vanamees", "mees nagu orkester"],
    "mees": ["machomees", "vanamees", "elumees", "alfaisane", "vahetu realist"],
    "naine": ["emane", "lind", "liha", "beibed", "tutt"],
    "party": ["party in my pants", "disko", "pidu", "klubis", "tantsupõrand"],
    "raha": ["papp", "krediit", "suurraha", "ränka raha", "kõik on makstud"],
    "sõber": ["bro", "homie", "kaveri", "meie talli", "ülemus"],
    "muusika": ["biit", "räpp", "rokk", "hitt", "lugu"],
    "tuju": ["tuju on ultra", "mood", "vibe", "meeleolu", "feelingud"],
    "linn": ["Tallinn", "pealinn", "tsentrum", "linnapilt", "tänav"],
    "öö": ["öine", "nightman", "kesköö", "öödisko", "pimedus"]
};
